### ISSUE TITLE
no dev_config.json

### ISSUE THREAD

**Issue by lukekarrys** [HenrikJoreteg/humanjs-sample-app#1]
Running the instructions:

```
git clone git@github.com:HenrikJoreteg/humanjs-sample-app.git
cd humanjs-sample-app/
npm i
node server
```

and got the error `No config file found for dev` from `getconfig` since there is no dev_config.json. Should this be included in the repo? Or should there be a setup instruction?

```
$ node server
No config file found for dev
We couldn't find anything at: /Users/lukekarrys/Projects/andyet/humanjs-sample-app/dev_config.json

/Users/lukekarrys/Projects/andyet/humanjs-sample-app/node_modules/getconfig/getconfig.js:36
    throw e;
          ^
Error: ENOENT, no such file or directory '/Users/lukekarrys/Projects/andyet/humanjs-sample-app/dev_config.json'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/Users/lukekarrys/Projects/andyet/humanjs-sample-app/node_modules/getconfig/getconfig.js:32:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lukekarrys/Projects/andyet/humanjs-sample-app/server.js:5:14)
```

**Comment by HenrikJoreteg** [comment]
i had one locally, but it was in gitignore for some reason. fixing....
